apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  type: LoadBalancer
  ports:
    - name: '5000'
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: nodejs
status:
  loadBalancer: {}
